# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (c) 2026 Rajaganapathy M
# For commercial licensing: https://github.com/RajaGanapathyM/kattalai

"""
Codex App — LLM Knowledge-Base Manager
Manages a tree of Markdown documents under ./knowledge_base with an
auto-maintained index.md table of contents.

All mutating operations require explicit user approval via a Catppuccin-themed
tkinter permission dialog before any file-system change is made.
"""

import json
import os
import re
import shutil
from datetime import datetime
from pathlib import Path
import tkinter as tk

import sys

apps_path = Path(__file__).resolve().parent.parent.parent
sys.path.append(str(apps_path))
import se_app_utils
from se_app_utils.soulengine import soul_engine_app


# ── Catppuccin Mocha palette ───────────────────────────────────────────────────
_BG      = "#1e1e2e"
_SURFACE = "#313244"
_TEXT    = "#cdd6f4"
_SUBTEXT = "#a6adc8"
_BLUE    = "#89b4fa"
_GREEN   = "#a6e3a1"
_RED     = "#f38ba8"
_YELLOW  = "#f9e2af"

# ── Dialog copy per command ────────────────────────────────────────────────────
_DIALOG_MESSAGES: dict[str, str] = {
    "new":    "Allow creating a new knowledge document at this path?\n"
              "The index.md will be updated automatically.",
    "mkdir":  "Allow creating a new category folder at this path?",
    "edit":   "Allow overwriting the full content of this knowledge document?",
    "append": "Allow appending new content to this knowledge document?",
    "delete": "Allow permanently deleting this knowledge document?\n"
              "The index.md will be updated automatically. This cannot be undone.",
    "move":   "Allow moving / renaming this knowledge document?\n"
              "The index.md will be updated automatically.",
    "link":   "Allow adding a cross-reference link from the source document\n"
              "to the destination document?",
}

# ── Constants ─────────────────────────────────────────────────────────────────
_KB_ROOT_REL  = Path("./knowledge_base")   # relative to cwd at runtime
_INDEX_NAME   = "index.md"
_RELATED_HDR  = "## Related"
_INDEX_HEADER = """\
# Knowledge Base Index

<!-- AUTO-MANAGED by Codex App — do not edit this file manually -->

## Table of Contents

"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _kb_root() -> Path:
    """Always resolved at call time so cwd changes are respected."""
    return (_KB_ROOT_REL).resolve()


def _index_path() -> Path:
    return _kb_root() / _INDEX_NAME


def _resolve_kb(raw: str) -> Path:
    """
    Accept paths in any of these forms and normalise to an absolute Path:
      ./knowledge_base/foo.md        (workspace-relative, includes kb root)
      knowledge_base/foo.md          (same without leading ./)
      ./foo.md  or  foo.md           (relative to kb root)
      /absolute/path/foo.md          (passed through)
    """
    p = Path(os.path.expanduser(raw))
    if p.is_absolute():
        return p
    resolved = (Path.cwd() / p).resolve()
    # If the path already sits under the kb root, return as-is.
    try:
        resolved.relative_to(_kb_root())
        return resolved
    except ValueError:
        # Treat as relative to kb root
        return (_kb_root() / p).resolve()


def _now() -> str:
    return datetime.now().isoformat()


def _extract_title(path: Path) -> str:
    """Return the first H1 heading from a markdown file, or a humanised stem."""
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                return line[2:].strip()
    except Exception:
        pass
    return path.stem.replace("_", " ").replace("-", " ").title()


def _extract_description(path: Path) -> str:
    """Return the first blockquote line (> …) as a description, if present."""
    try:
        for line in path.read_text(encoding="utf-8").splitlines():
            stripped = line.strip()
            if stripped.startswith("> "):
                return stripped[2:].strip()
    except Exception:
        pass
    return ""


def _rel_display(path: Path) -> str:
    """Return a workspace-relative display path (./knowledge_base/…)."""
    try:
        rel = path.relative_to(Path.cwd())
        return "./" + str(rel).replace("\\", "/")
    except ValueError:
        return str(path)


# ── Index management ──────────────────────────────────────────────────────────

def _rebuild_index() -> None:
    """
    Scan the whole knowledge-base tree and rewrite index.md from scratch.
    Each .md entry (excluding index.md itself) is listed with its title,
    workspace-relative path, and optional description.
    """
    kb = _kb_root()
    idx = _index_path()
    kb.mkdir(parents=True, exist_ok=True)

    md_files = sorted(
        (f for f in kb.rglob("*.md") if f.resolve() != idx.resolve()),
        key=lambda f: f.relative_to(kb)
    )

    lines: list[str] = [_INDEX_HEADER]

    if not md_files:
        lines.append("_No knowledge documents yet._\n")
    else:
        for i, md in enumerate(md_files, 1):
            title = _extract_title(md)
            disp  = _rel_display(md)
            desc  = _extract_description(md)
            desc_part = f"  \n  _{desc}_" if desc else ""
            lines.append(f"{i}. **{title}**  \n   `{disp}`{desc_part}\n")

    idx.write_text("\n".join(lines), encoding="utf-8")


def _ensure_kb_ready() -> None:
    kb = _kb_root()
    kb.mkdir(parents=True, exist_ok=True)
    if not _index_path().exists():
        _rebuild_index()


# ── Permission dialog ─────────────────────────────────────────────────────────

def _request_permission(command: str, context: dict) -> bool:
    """
    Blocking Catppuccin Mocha tkinter dialog.
    Returns True → Allow, False → Deny / window closed.
    """
    result = {"allowed": False}

    root = tk.Tk()
    root.title("Codex — Permission Required")
    root.resizable(False, False)
    root.configure(bg=_BG)

    root.update_idletasks()
    w, h = 500, 290
    x = (root.winfo_screenwidth()  - w) // 2
    y = (root.winfo_screenheight() - h) // 2
    root.geometry(f"{w}x{h}+{x}+{y}")

    # ── Icon + title row ──────────────────────────────────────────────────────
    hdr = tk.Frame(root, bg=_BG)
    hdr.pack(fill="x", padx=20, pady=(16, 0))

    tk.Label(hdr, text="📚", font=("Segoe UI Emoji", 22),
             fg=_YELLOW, bg=_BG).pack(side="left")
    tk.Label(hdr,
             text=f"Codex — Permission Required: {command.upper()}",
             font=("Segoe UI", 11, "bold"),
             fg=_TEXT, bg=_BG).pack(side="left", padx=(10, 0))

    # ── Message ───────────────────────────────────────────────────────────────
    msg = _DIALOG_MESSAGES.get(command, f"Allow executing '{command}'?")
    tk.Label(root, text=msg, font=("Segoe UI", 9),
             fg=_SUBTEXT, bg=_BG,
             wraplength=460, justify="left").pack(fill="x", padx=20, pady=(8, 0))

    # ── Context details box ───────────────────────────────────────────────────
    box = tk.Frame(root, bg=_SURFACE)
    box.pack(fill="x", padx=20, pady=10)

    for key, val in context.items():
        row = tk.Frame(box, bg=_SURFACE)
        row.pack(fill="x", padx=10, pady=2)
        tk.Label(row, text=f"{key}:", font=("Consolas", 9, "bold"),
                 fg=_BLUE, bg=_SURFACE, width=14, anchor="w").pack(side="left")
        tk.Label(row, text=str(val), font=("Consolas", 9),
                 fg=_TEXT, bg=_SURFACE, anchor="w").pack(side="left", fill="x")

    # ── Buttons ───────────────────────────────────────────────────────────────
    btns = tk.Frame(root, bg=_BG)
    btns.pack(pady=(0, 16))

    def _allow():
        result["allowed"] = True
        root.destroy()

    def _deny():
        result["allowed"] = False
        root.destroy()

    tk.Button(btns, text="✕  Deny",  command=_deny,
              font=("Segoe UI", 10, "bold"), cursor="hand2",
              bg=_RED,   fg=_BG, activebackground="#eba0ac",
              relief="flat", padx=18, pady=6).pack(side="left", padx=(0, 12))

    tk.Button(btns, text="✓  Allow", command=_allow,
              font=("Segoe UI", 10, "bold"), cursor="hand2",
              bg=_GREEN, fg=_BG, activebackground="#94e2d5",
              relief="flat", padx=18, pady=6).pack(side="left")

    root.protocol("WM_DELETE_WINDOW", _deny)
    root.lift()
    root.attributes("-topmost", True)
    root.focus_force()
    root.mainloop()

    return result["allowed"]


# ── App class ─────────────────────────────────────────────────────────────────

class CodexApp(soul_engine_app):

    def __init__(self):
        super().__init__(app_name="Codex App")
        _ensure_kb_ready()

    # ── Standard response builders ────────────────────────────────────────────

    def _ok(self, command: str, **extra) -> dict:
        return {
            "status": "success",
            "command": command,
            "permission_dialog_shown": True,
            "user_confirmed": True,
            "timestamp": _now(),
            **extra,
        }

    def _denied(self, command: str, **extra) -> dict:
        return {
            "status": "denied",
            "command": command,
            "permission_dialog_shown": True,
            "user_confirmed": False,
            "timestamp": _now(),
            **extra,
        }

    def _err(self, command: str, code: str, reason: str, **extra) -> dict:
        return {
            "status": "error",
            "command": command,
            "error_code": code,
            "reason": reason,
            **extra,
        }

    # ── Argument parser ───────────────────────────────────────────────────────

    @staticmethod
    def _parse_args(args: list[str]) -> dict:
        parsed: dict = {}
        for token in args:
            if "=" in token:
                k, _, v = token.partition("=")
                parsed[k.strip()] = v.strip().strip('"').strip("'")
            else:
                parsed.setdefault("_bare", []).append(token)
        return parsed

    # ── Dispatcher ────────────────────────────────────────────────────────────

    async def process_command(self, se_interface, args):
        if not args:
            se_interface.send_message(json.dumps(
                self._err("?", "no_command", "No command provided.")))
            return

        command = args[0].lower()
        kv = self._parse_args(args[1:])

        handler = getattr(self, f"_cmd_{command}", None)
        if handler is None:
            se_interface.send_message(json.dumps(self._err(
                command, "unknown_command",
                f"Unknown command '{command}'. "
                "Valid commands: index, read, search, "
                "new, mkdir, edit, append, delete, move, link"
            )))
            return

        try:
            result = await handler(se_interface, kv)
        except Exception as exc:
            result = self._err(command, "runtime_error", str(exc))

        se_interface.send_message(json.dumps(result))

    # ══════════════════════════════════════════════════════════════════════════
    # READ commands
    # ══════════════════════════════════════════════════════════════════════════

    async def _cmd_index(self, _si, _kv: dict) -> dict:
        """Return the full index.md content and a parsed entries list."""
        _ensure_kb_ready()
        idx = _index_path()
        raw = idx.read_text(encoding="utf-8")

        # Parse entries for structured access
        entries = []
        kb = _kb_root()
        for md in sorted(
            (f for f in kb.rglob("*.md") if f.resolve() != idx.resolve()),
            key=lambda f: f.relative_to(kb)
        ):
            entries.append({
                "title":       _extract_title(md),
                "path":        _rel_display(md),
                "description": _extract_description(md),
            })

        return {
            "status":  "success",
            "command": "index",
            "index_path": _rel_display(idx),
            "total_documents": len(entries),
            "entries": entries,
            "content": raw,
        }

    async def _cmd_read(self, _si, kv: dict) -> dict:
        """Read and return the content of a knowledge document."""
        raw = kv.get("path")
        if not raw:
            return self._err("read", "missing_argument", "Missing 'path' argument.")

        path = _resolve_kb(raw)
        if not path.exists():
            return self._err("read", "path_not_found",
                             f"Document does not exist: {_rel_display(path)}")
        if not path.is_file():
            return self._err("read", "not_a_file",
                             f"Path is not a file: {_rel_display(path)}")
        if path.suffix.lower() != ".md":
            return self._err("read", "not_markdown",
                             "Only .md files are managed by Codex App.")

        content = path.read_text(encoding="utf-8")
        return {
            "status":  "success",
            "command": "read",
            "path":    _rel_display(path),
            "title":   _extract_title(path),
            "content": content,
        }

    async def _cmd_search(self, _si, kv: dict) -> dict:
        """Full-text search across all knowledge documents."""
        pattern = kv.get("pattern", "")
        if not pattern:
            return self._err("search", "missing_argument", "Missing 'pattern' argument.")

        raw_path = kv.get("path", "")
        scope = _resolve_kb(raw_path) if raw_path else _kb_root()

        if not scope.exists():
            return self._err("search", "path_not_found",
                             f"Search scope does not exist: {_rel_display(scope)}")

        regex = re.compile(re.escape(pattern), re.IGNORECASE)
        matches = []
        files = [scope] if scope.is_file() else scope.rglob("*.md")

        for fp in files:
            fp = Path(fp)
            if not fp.is_file() or fp.suffix.lower() != ".md":
                continue
            try:
                for lineno, line in enumerate(
                    fp.read_text(encoding="utf-8", errors="replace").splitlines(), 1
                ):
                    if regex.search(line):
                        matches.append({
                            "path":        _rel_display(fp),
                            "title":       _extract_title(fp),
                            "line_number": lineno,
                            "snippet":     line.strip(),
                        })
            except Exception:
                pass

        return {
            "status":  "success",
            "command": "search",
            "pattern": pattern,
            "scope":   _rel_display(scope),
            "total_matches": len(matches),
            "matches": matches,
        }

    # ══════════════════════════════════════════════════════════════════════════
    # WRITE commands
    # ══════════════════════════════════════════════════════════════════════════

    async def _cmd_new(self, si, kv: dict) -> dict:
        """Create a new knowledge document and update index.md."""
        raw = kv.get("path")
        if not raw:
            return self._err("new", "missing_argument", "Missing 'path' argument.")

        title       = kv.get("title", "").strip()
        description = kv.get("description", "").strip()
        path        = _resolve_kb(raw)

        if path.exists():
            return self._err("new", "already_exists",
                             f"Document already exists: {_rel_display(path)}")
        if path.suffix.lower() != ".md":
            return self._err("new", "invalid_extension",
                             "Knowledge documents must have a .md extension.")

        # Derive title from path if not supplied
        if not title:
            title = path.stem.replace("_", " ").replace("-", " ").title()

        ctx = {"path": _rel_display(path), "title": title}
        if description:
            ctx["description"] = description

        if not _request_permission("new", ctx):
            return self._denied("new", path=_rel_display(path))

        path.parent.mkdir(parents=True, exist_ok=True)

        # Scaffold the document
        body_lines = [f"# {title}", ""]
        if description:
            body_lines += [f"> {description}", ""]
        body_lines += [
            "<!-- Add your content below -->", "",
            "## Overview", "",
            "_Write your overview here._", "",
        ]
        path.write_text("\n".join(body_lines), encoding="utf-8")

        _rebuild_index()

        return self._ok("new", path=_rel_display(path), title=title,
                        index_updated=True)

    async def _cmd_mkdir(self, si, kv: dict) -> dict:
        """Create a new category folder inside the knowledge base."""
        raw = kv.get("path")
        if not raw:
            return self._err("mkdir", "missing_argument", "Missing 'path' argument.")

        path = _resolve_kb(raw)

        if path.exists():
            return self._err("mkdir", "already_exists",
                             f"Path already exists: {_rel_display(path)}")

        if not _request_permission("mkdir", {"path": _rel_display(path)}):
            return self._denied("mkdir", path=_rel_display(path))

        path.mkdir(parents=True, exist_ok=True)
        return self._ok("mkdir", path=_rel_display(path))

    async def _cmd_edit(self, si, kv: dict) -> dict:
        """Overwrite the full content of an existing knowledge document."""
        raw     = kv.get("path")
        content = kv.get("content", "")
        if not raw:
            return self._err("edit", "missing_argument", "Missing 'path' argument.")
        if not content:
            return self._err("edit", "missing_argument",
                             "Missing 'content' argument. "
                             "Pass the complete new markdown content.")

        path = _resolve_kb(raw)
        if not path.exists():
            return self._err("edit", "path_not_found",
                             f"Document does not exist: {_rel_display(path)}")
        if path.suffix.lower() != ".md":
            return self._err("edit", "not_markdown",
                             "Only .md files are managed by Codex App.")

        if not _request_permission("edit", {"path": _rel_display(path),
                                            "size_now": f"{path.stat().st_size} bytes"}):
            return self._denied("edit", path=_rel_display(path))

        path.write_text(content, encoding="utf-8")
        _rebuild_index()          # title/description may have changed
        return self._ok("edit", path=_rel_display(path), index_updated=True)

    async def _cmd_append(self, si, kv: dict) -> dict:
        """Append new content to the end of an existing knowledge document."""
        raw     = kv.get("path")
        content = kv.get("content", "")
        if not raw:
            return self._err("append", "missing_argument", "Missing 'path' argument.")
        if not content:
            return self._err("append", "missing_argument", "Missing 'content' argument.")

        path = _resolve_kb(raw)
        if not path.exists():
            return self._err("append", "path_not_found",
                             f"Document does not exist: {_rel_display(path)}")

        if not _request_permission("append", {"path": _rel_display(path)}):
            return self._denied("append", path=_rel_display(path))

        with path.open("a", encoding="utf-8") as fh:
            fh.write(("\n" if not content.startswith("\n") else "") + content)

        return self._ok("append", path=_rel_display(path))

    async def _cmd_delete(self, si, kv: dict) -> dict:
        """Delete a knowledge document and update index.md."""
        raw = kv.get("path")
        if not raw:
            return self._err("delete", "missing_argument", "Missing 'path' argument.")

        path = _resolve_kb(raw)
        if not path.exists():
            return self._err("delete", "path_not_found",
                             f"Document does not exist: {_rel_display(path)}")
        if path.is_dir():
            return self._err("delete", "is_directory",
                             "Path is a directory. To remove a category folder "
                             "use a shell_app rmdir command.")
        if path.resolve() == _index_path().resolve():
            return self._err("delete", "protected_file",
                             "index.md is managed automatically and cannot be deleted.")

        if not _request_permission("delete", {"path": _rel_display(path),
                                              "title": _extract_title(path)}):
            return self._denied("delete", path=_rel_display(path))

        path.unlink()
        _rebuild_index()
        return self._ok("delete", path=_rel_display(path), index_updated=True)

    async def _cmd_move(self, si, kv: dict) -> dict:
        """Move or rename a knowledge document, then update index.md."""
        src_raw  = kv.get("src")  or kv.get("src_path")
        dest_raw = kv.get("dest") or kv.get("dest_path")
        if not src_raw or not dest_raw:
            return self._err("move", "missing_argument",
                             "Missing 'src' and/or 'dest' argument.")

        src  = _resolve_kb(src_raw)
        dest = _resolve_kb(dest_raw)

        if not src.exists():
            return self._err("move", "path_not_found",
                             f"Source does not exist: {_rel_display(src)}")
        if dest.exists():
            return self._err("move", "already_exists",
                             f"Destination already exists: {_rel_display(dest)}")
        if dest.suffix.lower() != ".md":
            return self._err("move", "invalid_extension",
                             "Destination must be a .md file.")

        if not _request_permission("move", {"src":  _rel_display(src),
                                            "dest": _rel_display(dest)}):
            return self._denied("move", src_path=_rel_display(src),
                                dest_path=_rel_display(dest))

        dest.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(src), str(dest))
        _rebuild_index()
        return self._ok("move", src_path=_rel_display(src),
                        dest_path=_rel_display(dest), index_updated=True)

    async def _cmd_link(self, si, kv: dict) -> dict:
        """
        Add a cross-reference link from src document to dest document.

        Validates existence of BOTH files, then appends / extends a
        '## Related' section at the bottom of src with a Markdown link
        pointing to dest (using a relative path).
        """
        src_raw  = kv.get("src")  or kv.get("src_path")
        dest_raw = kv.get("dest") or kv.get("dest_path")
        label    = kv.get("label", "").strip()

        if not src_raw or not dest_raw:
            return self._err("link", "missing_argument",
                             "Missing 'src' and/or 'dest' argument.")

        src  = _resolve_kb(src_raw)
        dest = _resolve_kb(dest_raw)

        # ── Existence checks (no permission needed yet) ───────────────────────
        errors = []
        if not src.exists():
            errors.append(f"Source does not exist: {_rel_display(src)}")
        elif src.suffix.lower() != ".md":
            errors.append(f"Source is not a .md file: {_rel_display(src)}")

        if not dest.exists():
            errors.append(f"Destination does not exist: {_rel_display(dest)}")
        elif dest.suffix.lower() != ".md":
            errors.append(f"Destination is not a .md file: {_rel_display(dest)}")

        if errors:
            return self._err("link", "file_not_found", " | ".join(errors),
                             src_path=_rel_display(src),
                             dest_path=_rel_display(dest))

        if src.resolve() == dest.resolve():
            return self._err("link", "self_link",
                             "src and dest point to the same file.")

        # ── Build the relative href from src's directory to dest ──────────────
        try:
            rel_href = os.path.relpath(str(dest), str(src.parent))
            rel_href = rel_href.replace("\\", "/")
        except ValueError:
            rel_href = _rel_display(dest)

        dest_title  = _extract_title(dest)
        link_label  = label if label else dest_title
        link_line   = f"- [{link_label}]({rel_href})"

        if not _request_permission("link", {
            "src":   _rel_display(src),
            "dest":  _rel_display(dest),
            "label": link_label,
        }):
            return self._denied("link", src_path=_rel_display(src),
                                dest_path=_rel_display(dest))

        # ── Inject link into src ──────────────────────────────────────────────
        src_text = src.read_text(encoding="utf-8")

        if _RELATED_HDR in src_text:
            # Append inside existing Related section
            src_text = src_text.rstrip()
            # Find the section and append after its last line
            idx_h = src_text.index(_RELATED_HDR)
            # Look for the next ## heading after Related
            after  = src_text[idx_h + len(_RELATED_HDR):]
            next_h = re.search(r"\n## ", after)
            if next_h:
                insert_pos = idx_h + len(_RELATED_HDR) + next_h.start()
                src_text = (src_text[:insert_pos].rstrip()
                            + "\n" + link_line
                            + "\n\n"
                            + src_text[insert_pos:].lstrip())
            else:
                src_text = src_text + "\n" + link_line + "\n"
        else:
            # Append a brand-new Related section
            src_text = src_text.rstrip() + f"\n\n{_RELATED_HDR}\n\n{link_line}\n"

        src.write_text(src_text, encoding="utf-8")

        return self._ok("link",
                        src_path=_rel_display(src),
                        dest_path=_rel_display(dest),
                        link_added=link_line)


# ── Entry point ────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    app = CodexApp()
    app.run_repl()