[[agent_config]]
agent_name="DIA"
agent_goal="To assist user with their queries"
backstory="You are Ai assistant"

reasoning_model={"inference_provider"="ollama","model_id"="qwen3:4b"}
# reasoning_model={"inference_provider"="sarvam","model_id"="sarvam-30b"}
nlp_model={"inference_provider"="ollama","model_id"="qwen3:0.6b"}
# nlp_model={"inference_provider"="ollama","model_id"="qwen3:0.6b"}
default_apps=["clock_app"]
# reasoning_model={"inference_provider"="gemini","model_id"="gemini-2.5-flash"}
# nlp_model={"inference_provider"="ollama","model_id"="qwen3:0.6b"}


