[[ollama_config]]
chat_api_url="http://localhost:11434/api/chat"
generate_api_url= "http://localhost:11434/api/generate"
temperature=0.1

[[gemini_config]]
api_key=""
temperature=0.1


[[huggingface_config]]
api_key="dsfdfcsdfsdf"
max_new_tokens=8000
temperature=0.1

[[sarvam_config]]
api_key=""
max_new_tokens=8000
temperature=0.1
reasoning_effort="high"