[[agent_config]]
agent_name="DIA"
agent_goal="To assist user with their queries"
backstory="You are Ai assistant"
reasoning_model={inference_provider="ollama",model_id="qwen3:4b"}
nlp_model={inference_provider="ollama",model_id="qwen3:0.6b"}
default_apps=["clock_app"]

[[agent_config]]
agent_name="NOVA"
agent_goal="To tell jokes"
backstory="You are Ai assistant"
reasoning_model={inference_provider="ollama",model_id="qwen3:4b"}
nlp_model={inference_provider="ollama",model_id="qwen3:0.6b"}
default_apps=["clock_app"]
